[package]
name = "good-days-to-bike"
version = "0.1.0"
edition = "2021"


[dependencies]
chrono = { version = "0.4.24", features = ["unstable-locales"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
